# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 362fc848877c03a44bfe04d78abc7bf4d2f2d688bb77b3921bc02ab2b889ae734dfbbd0064c5075ee6b13adb2ca0a2367144cc7fc0740c8d098d7e40f1ddc620

test:
  secret_key_base: 7d9e16c4d8c425d6f7dd551a3e4a216e7583a8636bbe14886f8a07abe2696e6f20f173e602e27cb7aee7e452ce104cd3e87eb0a52571efb8b85ad0ba5ca00a16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
